[2023-12-12T09:21:50.774+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_bipo_dag.call_api_and_process scheduled__2023-01-28T00:00:00+00:00 [queued]>
[2023-12-12T09:21:50.790+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_bipo_dag.call_api_and_process scheduled__2023-01-28T00:00:00+00:00 [queued]>
[2023-12-12T09:21:50.791+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-12T09:21:50.818+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): call_api_and_process> on 2023-01-28 00:00:00+00:00
[2023-12-12T09:21:50.826+0000] {standard_task_runner.py:57} INFO - Started process 3884 to run task
[2023-12-12T09:21:50.829+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_bipo_dag', 'call_api_and_process', 'scheduled__2023-01-28T00:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/bipo_employee_info.py', '--cfg-path', '/tmp/tmpder13vj4']
[2023-12-12T09:21:50.832+0000] {standard_task_runner.py:85} INFO - Job 231: Subtask call_api_and_process
[2023-12-12T09:21:50.850+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-12-12T09:21:50.895+0000] {task_command.py:416} INFO - Running <TaskInstance: my_bipo_dag.call_api_and_process scheduled__2023-01-28T00:00:00+00:00 [running]> on host e1a26a98da8f
[2023-12-12T09:21:51.000+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_bipo_dag' AIRFLOW_CTX_TASK_ID='call_api_and_process' AIRFLOW_CTX_EXECUTION_DATE='2023-01-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-28T00:00:00+00:00'
[2023-12-12T09:22:41.394+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to success. Terminating instance.
[2023-12-12T09:22:41.397+0000] {process_utils.py:131} INFO - Sending 15 to group 3884. PIDs of all processes in the group: [3884]
[2023-12-12T09:22:41.398+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 3884
[2023-12-12T09:22:41.399+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-12-12T09:22:41.452+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=3884, status='terminated', exitcode=0, started='09:21:50') (3884) terminated with exit code 0
